### PR TITLE
Make code look prettier

### PR DESCRIPTION
**Pull request by shashkambh**
I didn't do any substantial logic changes - just pulled some stuff into a function and changed the cascading if/else into a switch.

I took out the Chase exception as well because he doesn't teach here anymore.

### CODE REVIEW

**Comment by smkanvinde** [comment]
The Chase exception is there for the meme. You know there are upperclassmen who would protest if it weren't there LOL. Plus we're holding out for the hope that he comes back.

**Comment by smkanvinde** [comment]
Leaving this one up to @kuthalam

**Comment by kuthalam** [comment]
The code looks great, thanks! Just to be sure, has it been tested?

**Comment by shashkambh** [comment]
Nothing extensive, but I ran it a few times.

**Comment by kuthalam** [comment]
Sounds good to me! Will get it approved.

EDIT: May take some time. Need to handle some merge conflicts manually.

**Comment by kuthalam** [comment]
Did the manual merge resolution and it's all working as far as I can tell.

**Pull request closed without merging**
